---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-secrets
  namespace: ecommerce
spec:
  encryptedData:
    JWT_SECRET: AgAbzPFRsm8wHYI3D/fG5Dr9SmNUNQbxWm1IyIBTLcrdSs88t+q+c6q7cgCE84KgdQ+DUkxZh+gzgM36t/diqQxdnzvX1v5F6qlApIaq0iX1OO5jm25Mzo/GZf/ZVWL9RRGQE7Q2pjUVpwpueC5gvTKf4YeMsUGwS8LzULq/5etacH0QeFOF0wEktICUmKThDKtbRY7N6zE/jDWboVwKQLpQb+AFPnTFjSjIgIjko4KZ3e+kMC2sbQqt0oYKC3om2jVvydn6AYks66r2paTx/6qu15IbCaj4knNi+OXa7ojicznmi4ib3gUg8ygId2JxKn4+afJxmAcNPMMGCtIOT0eVRSiXNGPUqO+UXQbaT0ReRssnfLBZDxV8hn+s1xQO3HW+2OJ9IV8YmoMWjZmlgHnr4zbg3awu6G6AmNpFqkT1O52aSONC4cmYqiB73AXhLqegXeT2kpYmHLHCIEFPJoA2mbOH6YArQz6Km4D0CmZXw80S/Tl1/NCNR8v15fyW/fHIiNJbcRx8l+XYQFQdn0UPvQmsYMItkMY2uIsaQx21+wWu9OMwiOqS7vvx22i3L3xlBZzPmeasCFIKoPlTNlXQ5D8xCXe5hOYAtykk8/pfaIvzW/OMLs16C71pY3HhAZSpy7l8niUd3f/Q+bTzNpmxWHDgYP30s4CeaSJ0ZGoINiEp8xfX12m5UVntbEzfQCo8m49JQudgR5Ois/2LgTBD
  template:
    metadata:
      creationTimestamp: null
      name: user-service-secrets
      namespace: ecommerce
